### ISSUE TITLE
Handle command input

### ISSUE THREAD

**Issue by Jerrylum** [Jerrylum/ProtocolDiagram#3]
**Is your feature request related to a problem? Please describe.**
We need to handle the command from the standard input.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crapper** [comment]
For BooleanT:
Isn't it will be better for do the s.toLowerCase() and just check on true and false is better? 
I can see the case itself wanted to solve some time ppl just all in lower or T or F in upper case. 
But this toLowerCase() just allow those extra cases like
TrUe or TRUE... can be also detacted.
