### ISSUE TITLE
feat: Change checking in finding firststop while loop of Parameter class

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#32]
![image](https://user-images.githubusercontent.com/26902835/195519539-e01e56c4-bdca-4115-b54d-4031eda3db58.png)
In the Parameter class, firststop is the index for the next end or delimiter in the buffer, however, as shown in above, it directly trys to do compare with char ' ', which should be done in !Token.isDelimiter(buffer.peek(i)).

**Comment by koolerkx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change checking in finding firststop while loop of Parameter class](https://trello.com/c/pZc9r2SI/18-change-checking-in-finding-firststop-while-loop-of-parameter-class)
