### ISSUE TITLE
Question: Does this case statement in Parameter is needed?

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#33]
![image](https://user-images.githubusercontent.com/26902835/195523954-681137ea-33b2-4068-8676-d4310df72ef2.png)
As I see in the if statement in StringT only check whether the return is null or not, why the other two didn't do this?

In Parameter class, there has a attribute called firststop to preview and store the index for next end or space in buffer. However, since the BooleanT and NumberT parsing will already set the buffer index to in the next end or space during a successful run, unless it just mean it cannot be parse to those object and return null. So is this checking in firststop with buffer current index after pasing is important?

**Comment by Jerrylum** [comment]
I see.

I think it is necessary for NumberT but not BooleanT. For example:
```java
assertEquals(Parameter.parse(new CodePointBuffer("3.14h")).getDouble(), 3.14, 0.0001);
```
should not be equal.

So finally, I think it is safe for you to remove the fullStop check in the BooleanT if statement.
