### ISSUE TITLE
Parameter parsing is incorrect if a chunk starts with a number

### ISSUE THREAD

**Issue by Jerrylum** [Jerrylum/ProtocolDiagram#35]
**Describe the bug**
In #34 (commit `f7d2ec03310ac4b0cc00544a1e1b00c7efa447ea`), the parsing result of the parameter is incorrect.

**To Reproduce**
The following testcase should be failed:
`assertEquals(Parameter.parse(new CodePointBuffer("3.14h")).getString(), "h");`

**Expected behavior**
`3.14h` should be parsed as string `3.14h` but not `h`

**Comment by crapper** [comment]
![image](https://user-images.githubusercontent.com/26902835/195623071-93953948-0faf-4dee-b613-817b9f71fdce.png)
![image](https://user-images.githubusercontent.com/26902835/195623163-7fb19b10-9e67-42ba-9523-68a28b8fee9f.png)
Solved by handle the wrong index moving
