### ISSUE TITLE
Saving file name with directory name will still be available

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#37]
The saving command still works when the argument for the saving json filename is a directory, shown as follows:
![image](https://user-images.githubusercontent.com/26902835/195975400-f0d6eb8c-58da-4724-9ad6-9da945a43c28.png)
![image](https://user-images.githubusercontent.com/26902835/195975454-fc07859b-4e3f-48e2-a772-5ebb7a794f6f.png)

For case filename = .. and ./, they should be treat as directory instead of adding a .json after it and treat them as a filename

**Comment by Jerrylum** [comment]
Ah, I see. The user should be able to save files anywhere in computer. I think this is intended, but I can come up with a better apporach.

The tool adds `.json` to the end of the path if the path doesn't end with `.json`, which is not the best apporach. For example:

`save ""` saves `.json` to the current directory. However, it should be rejected.
`save hello` saves `hello.json` to the current directory and it is correct.
`save hello.js` saves `hello.js.json` to the current directory and it should be `hello.js`
`save .` saves `..json` to the current directory. However, it should be rejected.
`save ..` saves `...json` to the current directory. However, it should be rejected.
`save ./` saves `.json` to the current directory. However, it should be rejected.
`save ./hello` saves `hello.json` to the current directory and it is correct.
`save ./hello.js` saves `hello.js.json` to the current directory and it should be `hello.js`
`save ./.` saves `..json` to the current directory. However, it should be rejected.
`save ./..` saves `...json` to the current directory. However, it should be rejected.
`save ../` saves `.json` to the parent directory. However, it should be rejected.
`save ../hello` saves `hello.json` to the parent directory and it is correct.
`save ../hello.js` saves `hello.js.json` to the parent directory and it should be `hello.js`
and so on...

In addition, the file path message is not good enough. I will come up with a better solution.

**Comment by Jerrylum** [comment]
I pushed a new commit to the branch now, here is the example input and output of the new method:

Input:
```
System.out.println(FileSystem.resolvePath(""));
System.out.println(FileSystem.resolvePath("  "));
System.out.println(FileSystem.resolvePath("./ "));
System.out.println(FileSystem.resolvePath("hello"));
System.out.println(FileSystem.resolvePath("hello.js"));
System.out.println(FileSystem.resolvePath("."));
System.out.println(FileSystem.resolvePath(".."));
System.out.println(FileSystem.resolvePath("./"));
System.out.println(FileSystem.resolvePath("./hello"));
System.out.println(FileSystem.resolvePath("./hello.js"));
System.out.println(FileSystem.resolvePath("./."));
System.out.println(FileSystem.resolvePath("./.."));
System.out.println(FileSystem.resolvePath("../"));
System.out.println(FileSystem.resolvePath("../hello"));
System.out.println(FileSystem.resolvePath("../hello.js"));
```

Output:
```
null
null
null
C:\Users\Jerrylum\Desktop\Project\git\ProtocolDiagram\hello.json
C:\Users\Jerrylum\Desktop\Project\git\ProtocolDiagram\hello.js
null
null
null
C:\Users\Jerrylum\Desktop\Project\git\ProtocolDiagram\hello.json
C:\Users\Jerrylum\Desktop\Project\git\ProtocolDiagram\hello.js
null
null
null
C:\Users\Jerrylum\Desktop\Project\git\hello.json
C:\Users\Jerrylum\Desktop\Project\git\hello.js
```
