### ISSUE TITLE
Wrong error message in Load command

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#39]
When the user input "load arg1 arg2", the system will response with too few argument instead of too many argument. 
I have fixed this through adding the return for >1 in the LoadCommnad.java.
![image](https://user-images.githubusercontent.com/26902835/195976119-6e7ce30f-c1ad-495e-ac58-d600fd7f5d3a.png)

After fixed:
![image](https://user-images.githubusercontent.com/26902835/195976135-f0b6fdcc-7546-4cda-a39c-c670183ea034.png)

**Comment by Jerrylum** [comment]
Got it! Thank you for the fixing.
