### ISSUE TITLE
Range of too many argument in DiscardCommand is incorrect

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#40]
![image](https://user-images.githubusercontent.com/26902835/195977915-fedc6702-1e5a-46ea-a501-bbd380900086.png)
The usage of discard should be directly called without any argument, so size > 1 will cause cases like discard arg1 is acceptable to the system:
![image](https://user-images.githubusercontent.com/26902835/195978037-ab708b90-647f-451f-a918-4472f4e3c6ae.png)

The problem is solved by changing the >1 to >0.

**Comment by Jerrylum** [comment]
Okay! Thank you.
