### ISSUE TITLE
Add existing protocol templates

### ISSUE THREAD

**Issue by Jerrylum** [Jerrylum/ProtocolDiagram#42]
**Is your feature request related to a problem? Please describe.**
The user can use an existing protocol as a template to start editing their diagram or just print the existing protocol diagram on the console.

**Comment by koolerkx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add existing protocol template](https://trello.com/c/0mT0lLdH/20-add-existing-protocol-template)

**Comment by koolerkx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Existing Protocol Templates](https://trello.com/c/zhvonss3/7-exist-protocol-viewer)
