### ISSUE TITLE
Redundent case statement for splice in DiagramUtil

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#52]
**Describe the bug**
In DiagramUtil, the pointer for the bottom and top bar should exit in the same time at the end, there should not exist any possible way for top and bottom pointer one of them can exit first. Unless the length of the row is not fixed as same.

**To Reproduce**
![image](https://user-images.githubusercontent.com/26902835/198824161-901a163e-fbef-4172-a3c8-bdacb21bf2ab.png)

**Expected behavior**
Redundent case checking should be removed.

**Comment by Jerrylum** [comment]
yea, I understand. The length of the row is not used to be the same as in the past. However, they must be the same now. So I think it is safe to modify the code to:

![image](https://user-images.githubusercontent.com/12783829/198824331-8bb4fbf1-e3a8-4cab-8176-9639a9d2bd79.png)

**Comment by crapper** [comment]
P.S. 
Since the row is in fixed sized, there should also be redundent for checking the bottomRowHasNext since the pointer will left in the same time.
![image](https://user-images.githubusercontent.com/26902835/198824885-0580e749-fe9d-49ac-a7bd-669c93f2af49.png)
