### ISSUE TITLE
Redundent checking for related size in setDisplayNameForAllFields

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#53]
**Describe the bug**
In setDisplayNameForAllFields, there has a checking for the size of related, which is list store the largest segments for each field, however there should not exist a case that a field does not have any segment representing it.  

**To Reproduce**
![image](https://user-images.githubusercontent.com/26902835/198825329-ff1e931b-eee2-4ccc-b2c5-054f365d61c4.png)

**Expected behavior**
The checking can be removed.

**Additional context**
#31 https://github.com/Jerrylum/ProtocolDiagram/issues/31#issuecomment-1277147156

**Comment by Jerrylum** [comment]
Make sense!
