### ISSUE TITLE
Wrong value setting for the checking in segment input size in Matrix

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#54]
**Describe the bug**
In Matrix constructor, it will directly return if the size is less than 6. However, consider the minimum case of segment list, which is divider + row + divider. Which will got 3 segment only.

**To Reproduce**
![image](https://user-images.githubusercontent.com/26902835/198827980-2a28c9eb-fffc-49e2-be39-75b55f29e954.png)

**Expected behavior**
32 bit length of f should be shown

**Comment by Jerrylum** [comment]
Oh no, you are right. I was thining about the `divider + divider + row + row + divider + divider` situlation but missed this situlation. Please help me to fix that >.<
