### ISSUE TITLE
About the comparison of CommandLine Class

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#9]
**Is your feature request related to a problem? Please describe.**
While doing the testing cases for CommandLine, I found out that due to the params of CommandLine is made of ArrayList of Parameter, but Parameter is not a record class, so it does not contain a proper equal compare override function. This makes the compare of the whole arraylist is not available which lead to many redundent cases need to be uses such to compare the deeper NumberT, BooleanT, StringT classes.

**Describe the solution you'd like**
Add a proper compare override function in CommandLine class

**Comment by Jerrylum** [comment]
Go ahead, please help me add the equal method to Parameter in the test branch.
